name: HTML to APK
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Install Cordova
        run: npm install -g cordova

      - name: Create Cordova Project
        run: |
          cordova create my-app com.example.helpme HelpMe
          cd my-app
          cordova platform add android
          rm -rf www/*
          unzip ../*.zip -d www/
          cordova build android --release

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: App-APK
          path: my-app/platforms/android/app/build/outputs/apk/release/app-release-unsigned.apk
          
